#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    ms_gateway-app:
        image: ms_gateway
        external_links:
            - ms_gateway-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - ms_gateway-cassandra:cassandra
            - ms_gateway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=https://admin:admin@hxline-registry.herokuapp.com//config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ms_gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    ms_gateway-mysql:
        extends:
            file: mysql.yml
            service: ms_gateway-mysql
    # Uncomment to have Cassandra working with the gateway
    # ms_gateway-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: ms_gateway-cassandra
    # ms_gateway-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: ms_gateway-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    ms_gateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ms_gateway-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
