version: '2'
services:
    ms_gateway-cassandra:
        container_name: ms_gateway-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/ms_gateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    ms_gateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: ms_gateway-cassandra-migration
        links:
            - ms_gateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
