version: '2'
services:
    ms_gateway-mysql:
        container_name: ms_gateway-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/ms_gateway/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ms_gateway
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
